version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
    ports:
      - "2181:2181"
  kafka-1:
    image: wurstmeister/kafka
    ports:
      - "9095:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9095
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_DIRS: /kafka/logs
      KAFKA_BROKER_ID: 500
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9095
      KAFKA_LISTENERS: PLAINTEXT://127.0.0.1:9095
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
     
  

  kafka-2:
    image: wurstmeister/kafka
    ports:
      - "9096:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9096
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_DIRS: /kafka/logs
      KAFKA_BROKER_ID: 501
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9096
      KAFKA_LISTENERS: PLAINTEXT://127.0.0.1:9096
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
     
  
  kafka-3:
    image: wurstmeister/kafka
    ports:
      - "9097:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9097
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_DIRS: /kafka/logs
      KAFKA_BROKER_ID: 502
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9097
      KAFKA_LISTENERS: PLAINTEXT://127.0.0.1:9097
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
   